canonical: https://gematik.de/fhir/ISiK/v2
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden ISiK-Basismodul Stufe 2 2.0.0
name: Implementierungsleitfaden ISiK-Basismodul Stufe 2 2.0.0
status: active
version: "2.0.0"
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: ISiK@gematik.de
dependencies:
  de.basisprofil.r4: 1.3.2
  hl7.fhir.r4.core: 4.0.1
  hl7.fhir.extensions.r5: 4.0.1